default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: PortfolioApp_development

test:
  <<: *default
  database: PortfolioApp_test

production:
  <<: *default
  database: PortfolioApp_production


